config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq', constraints: lambda { |request| request.session[:user_id].present? && User.find(request.session[:user_id]).present? }

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection
    get 'queued(/page/:page)', :action => :queued, :on => :collection
    get 'drafts(/page/:page)', :action => :drafts, :on => :collection
  end

  namespace :admin do
    get '/entries/tagged/:tag(/page/:page)'     => 'entries#tagged', constraints: { page: /\d+/ }, :as => 'tagged_entries'
    get '/entries/search'             => 'entries#search', :as => :search
    get '/entries/edit'               => 'entries#edit'
    get '/entries/share'              => 'entries#share'
    get '/entries/queued/organize'    => 'entries#organize_queue'
    post '/entries/queued/update'     => 'entries#update_queue'
    get '/entries/queued/schedule'    => 'publish_schedules#index'
    get '/equipment'                  => 'equipment#index'
    get '/map'                        => 'maps#index', :as => :map
    get '/map/photos.:format'         => 'maps#photos', :as => :map_markers
    get '/map/photo/:id.:format'      => 'maps#photo', :as => :map_photo

    resources :entries, concerns: :paginatable do
      member do
        get 'syndicate'
        get 'crops'
        get 'prints'
        patch 'publish'
        patch 'queue'
        patch 'draft'
        post 'instagram'
        post 'twitter'
        post 'twitter_banner'
        post 'facebook'
        post 'flickr'
        post 'flush_caches'
        post 'refresh_metadata'
        post 'tumblr'
      end
      collection do
        get 'queued'
        get 'drafts'
        get 'photo'
      end
      resources :photos, only: [] do
        member do
          get 'download'
          post 'crops'
        end
      end
    end

    resources :tags, only: [:index, :destroy, :show, :update], concerns: :paginatable do
      member do
        post 'add'
      end
    end

    resources :blogs, only: [:edit, :update] do
      member do
        post 'flush_caches'
      end
    end

    resources :cameras, only: [:edit, :update]
    resources :lenses, only: [:edit, :update]
    resources :films, only: [:edit, :update]
    resources :publish_schedules, only: [:create, :destroy]
    resources :tag_customizations, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :webhooks, except: [:show]
  end


  get '/(page/:page)'                  => 'entries#index',   constraints: { page: /\d+/ }, defaults: { format: 'html' }, :as => :entries
  get '/tagged/:tag(/page/:page)'      => 'entries#tagged',  constraints: { page: /\d+/ }, defaults: { format: 'html' }, :as => :tag
  get '/search'                        => 'entries#search', :as => :search
  get '/about'                         => 'blogs#about', :as => :about
  get '/oembed.:format'                => 'oembed#show', :as => :oembed
  match '/graphql'                     => 'graphql#options', via: :options
  post '/graphql'                      => 'graphql#execute'

  # Entries
  get '/e/:id'                              => 'entries#show',        constraints: { id: /\d+/ }, :as => :entry
  get '/preview/:preview_hash'              => 'entries#show',        defaults: { format: 'html' }, :as => :preview_entry
  get '/:year/:month/:day/:id(/:slug)'      => 'entries#show',        constraints: { id: /\d+/, year: /\d{1,4}/, month: /\d{1,2}/, day: /\d{1,2}/ }, defaults: { format: 'html' }, :as => :entry_long
  get '/related/:id.:format'                => 'entries#related',     defaults: { format: 'js' }, constraints: { id: /\d+/ }, :as => :related
  get '/related/:preview_hash.:format'      => 'entries#related',     defaults: { format: 'js' }, :as => :related_preview
  get '/amp/:year/:month/:day/:id(/:slug)'  => 'entries#amp',         constraints: { id: /\d+/, year: /\d{1,4}/, month: /\d{1,2}/, day: /\d{1,2}/ }, defaults: { format: 'html' }, :as => :entry_amp

  # Sitemaps
  get '/sitemap.:format'               => 'entries#sitemap_index', defaults: { format: 'xml' }, :as => :sitemap_index
  get '/sitemap/:page.:format'         => 'entries#sitemap', defaults: { format: 'xml' }, :as => :sitemap

  # Legacy routes & redirects
  get '/archive(/:year)(/:month)'      => 'legacy#home'
  get '/index.html'                    => 'legacy#home'
  get '/rss'                           => 'legacy#feed'
  get '/post/:tumblr_id(/:slug)'       => 'entries#tumblr', constraints: { tumblr_id: /\d+/ }

  #PWA
  get '/service_worker.js'             => 'service_worker#index', defaults: { format: 'js' }, :as => :service_worker

  # Feeds
  get '/feed(.:format)'             => 'entries#feed', defaults: { format: 'atom' }, :as => :feed
  get '/tagged/:tag/feed(.:format)' => 'entries#tag_feed', defaults: { format: 'atom' }, :as => :tag_feed

  # Admin
  get '/admin'                         => 'admin#index',      :as => :admin
  get '/auth/:provider/callback'       => 'sessions#create'
  get '/auth/failure'                  => 'sessions#failure'
  get '/signin'                        => 'sessions#new',     :as => :signin
  get '/signout'                       => 'sessions#destroy', :as => :signout

  # The rest
  get 'robots.:format'                 => 'robots#show', defaults: { format: 'txt' }
  root 'entries#index'
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  get '*unmatched_route', to: 'errors#file_not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publish_schedule.rb
class PublishSchedule < ApplicationRecord
  belongs_to :blog, touch: true, counter_cache: true, optional: true

  validates :hour, uniqueness: true
  
  after_save :touch_entries
  before_destroy :touch_entries
  
  def touch_entries
    self.blog.entries.queued.each(&:touch)
  end
end

app/controllers/admin/publish_schedules_controller.rb
class Admin::PublishSchedulesController < AdminController

  def index
    if stale?(@photoblog)
      @schedules = @photoblog.publish_schedules
      @page_title = 'Queue schedule'
      @queued_entries = @photoblog.entries.queued.count
      @new_schedule = PublishSchedule.new
      respond_to do |format|
        format.html
      end
    end
  end

  def create
    @schedule = PublishSchedule.new(schedule_params)
    @schedule.blog = @photoblog
    respond_to do |format|
      if @schedule.save
        flash[:success] = "Publishing schedule updated!"
        format.html { redirect_to admin_entries_queued_schedule_path }
      else
        flash[:warning] = 'The publishing schedule couldn’t be updated…'
        format.html { render :index }
      end
    end
  end

  def destroy
    schedule = PublishSchedule.find(params[:id])
    schedule.destroy
    respond_to do |format|
      format.html { redirect_to admin_entries_queued_schedule_path }
    end
  end

  private
  def schedule_params
    params.require(:publish_schedule).permit(:hour)
  end
end

app/helpers/admin/publish_schedules_helper.rb
module Admin::PublishSchedulesHelper

  def pretty_hour(hour)
    if hour == 0
      "12:00 am"
    elsif hour < 12
      "#{hour}:00 am"
    elsif hour == 12
      "12:00 pm"
    else
      "#{hour - 12}:00 pm"
    end
  end
end

app/views/admin/publish_schedules/_schedule.html.erb
<tr>
<td><%= pretty_hour(schedule.hour) %></td>
<td>
  <div class="buttons is-pulled-right">
    <%= link_to 'Delete', admin_publish_schedule_path(schedule.id), method: :delete, class: 'button is-danger is-small' %>
  </div>
</td>
</tr>

app/views/admin/publish_schedules/index.html.erb
<% cache @photoblog do %>
  <div class="level is-mobile">
    <div class="level-left">
      <div>
        <h1 class="title is-size-5-mobile">Queue schedule</h1>
        <h2 class="subtitle is-size-6-mobile">
          <% if @photoblog.publish_schedules_count == 0 %>
            Publishing is paused</h2>
          <% elsif @photoblog.publish_schedules_count == 1 %>
            Publishing once a day
          <% elsif @photoblog.publish_schedules_count == 2 %>
            Publishing twice a day
          <% else %>
            Publishing <%= pluralize_with_delimiter 'time', @photoblog.publish_schedules_count %> a day
          <% end %>
        </h2>
      </div>
    </div>
    <div class="level-right">
      <% if @queued_entries > 0 %>
        <div class="level-item">
          <a href="<%= admin_entries_queued_organize_path %>" class="button is-small">
            <span class="icon is-small">
              <i class="fas fa-sort"></i>
            </span>
            <span>Organize</span>
          </a>
        </div>
      <% end %>
    </div>
  </div>

  <hr class="hr">

  <%= form_for([:admin, @new_schedule]) do |f| %>
    <% hours = ([*0..23] - @schedules.map(&:hour)).map { |h| [pretty_hour(h), h]} %>
    <div class="field has-addons">
      <div class="control is-expanded">
        <div class="select is-fullwidth">
          <%= f.select :hour, options_for_select(hours) %>
        </div>
      </div>
      <div class="control">
        <%= f.submit 'Add to schedule', class: 'button' %>
      </div>
    </div>
    <p class="help">The current time zone is <%= Time.zone.name %>.</p>
  <% end %>

  <% if @schedules.present? %>
    <hr class="hr">
    <table class="table is-fullwidth is-hoverable is-striped">
      <thead>
        <tr>
        <th>Time</th>
        <th class="has-text-right-desktop">Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'schedule', collection: @schedules %>
      </tbody>
    </table>
  <% end %>

  <nav class="navbar is-fixed-bottom has-shadow">
    <div class="container">
      <div class="navbar-menu is-active">
        <div class="navbar-start">
          <div class="navbar-item">
            <a href="<%= queued_admin_entries_path %>" class="button is-small">
              <span class="icon is-small">
                <i class="fas fa-long-arrow-alt-left"></i>
              </span>
              <span>Go back</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </nav>
<% end %>